version: '3.8'

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .production.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .production.env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: